//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winformProject.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=18.222.232.191;Initial Catalog=smartParking;User ID=sa;Password=12345" +
            "678aA")]
        public string smartParkingConnectionString {
            get {
                return ((string)(this["smartParkingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=smartParking;Persist Security Info=True;User ID=sa;" +
            "Password=123")]
        public string smartParkingConnectionString1 {
            get {
                return ((string)(this["smartParkingConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=18.222.232.191;Initial Catalog=smartParking;Persist Security Info=Tru" +
            "e;User ID=sa;Password=12345678aA")]
        public string smartParkingConnectionString2 {
            get {
                return ((string)(this["smartParkingConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=phudeptrai3.cqc3kxuutqtm.us-east-2.rds.amazonaws.com;Initial Catalog=" +
            "smartParking;Persist Security Info=True;User ID=sa;Password=12345678")]
        public string smartParkingConnectionString3 {
            get {
                return ((string)(this["smartParkingConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database2.c69kwntmezi6.us-east-2.rds.amazonaws.com;Initial Catalog=sm" +
            "artParking;User ID=sa;Password=12345678")]
        public string smartParkingConnectionString4 {
            get {
                return ((string)(this["smartParkingConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database.c69kwntmezi6.us-east-2.rds.amazonaws.com;Initial Catalog=sma" +
            "rtParking;User ID=sa;Password=12345678")]
        public string smartParkingConnectionString5 {
            get {
                return ((string)(this["smartParkingConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=database2.c69kwntmezi6.us-east-2.rds.amazonaws.com;Initial Catalog=sm" +
            "artParking;Persist Security Info=True;User ID=sa;Password=12345678")]
        public string smartParkingConnectionString6 {
            get {
                return ((string)(this["smartParkingConnectionString6"]));
            }
        }
    }
}
